### ISSUE TITLE
Issue related to russross/blackfriday/v2

### ISSUE THREAD

**Issue by LeonardAukea** [vkuznecovas/mouthful#119]
Hi. I'm interested in getting Moutful up and running in addtion to my mkdocs. Looks like an awesome package. 

I noticed that there is a bit of a problem in building the package due to some curiosites going on in https://github.com/russross/blackfriday. This unfortunately has an effect on mouthful.

```
#7 52.27 Executing busybox-1.31.1-r16.trigger
#7 52.28 OK: 283 MiB in 52 packages
#7 52.32 + go get -d github.com/vkuznecovas/mouthful
#7 140.3 cannot find package "github.com/russross/blackfriday/v2" in any of:
#7 140.3        /usr/local/go/src/github.com/russross/blackfriday/v2 (from $GOROOT)
#7 140.3        /go/src/github.com/russross/blackfriday/v2 (from $GOPATH)
```

https://github.com/vkuznecovas/mouthful/blob/2719d37f232cf99fa7dee29ab40da8fb3b59dedd/global/sanitize.go#L5
https://github.com/vkuznecovas/mouthful/blob/2719d37f232cf99fa7dee29ab40da8fb3b59dedd/go.mod#L30
https://github.com/vkuznecovas/mouthful/blob/2719d37f232cf99fa7dee29ab40da8fb3b59dedd/go.mod#L21

It seems that you have also tired a workaround. But according to some of the discussions I've read the import in `sanitze.go` 
should be: 

```go
import (
    blackfriday "github.com/russross/blackfriday.v2"
)
```

I tried this combination as well but it did not resolve the issue...

I'm not a go developer, maybe you have an obvious fix in mind? 
Anyways. I just wanted to notify you that this problem exists. 

## Related issue 

https://github.com/russross/blackfriday/issues/565
There are more related issues but I have not found a cure yet. I tried a couple of suggested fixes as you seem to have done originally but I can't get any of them to work.

**Comment by vkuznecovas** [comment]
Should be fixed now, thanks for the report.
