### ISSUE TITLE
I am running the server localy. What's next?

### ISSUE THREAD

**Issue by oren** [vkuznecovas/mouthful#51]
How do I integrate this into a website? I have it running localy and I see 'no comments yet!'. I am probably missing some docs...

Thank you!

**Comment by vkuznecovas** [comment]
Thanks for noticing, not even sure how this slipped my mind. I've added the client side documentation in #52. In short, include this in your html

```
<div id="mouthful-comments" data-url="http://localhost:8080"></div>
<script src="https://api.dizzy.zone/client.js"></script>
```


Also pardon the long response time, currently on a bit of a vacation.
