### ISSUE TITLE
Publish Docker image to Docker Hub

### ISSUE THREAD

**Issue by prologic** [vkuznecovas/mouthful#53]
It would be nice if you set up an "Automated Build" to the [Docker Hub](https://hub.docker.com)

**Comment by vkuznecovas** [comment]
👍 Will work on this once I get the free time

**Comment by prologic** [comment]
Once you fix vkuznecovas/mouthful#54 this is pretty trivial. Just
signup/login to hub.docker.com and created an Automated Build of this repo.


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by vkuznecovas** [comment]
After #57 I've created a docker repo here -> https://hub.docker.com/r/vkuznecovas/mouthful/
