### ISSUE TITLE
Admin page redirection

### ISSUE THREAD

**Issue by seqizz** [vkuznecovas/mouthful#67]
Hi again,

While using mouthful behind nginx (with local binding), there seems to be no way to reach to the admin panel. I redirected to /comment-engine/ URL with proxy_pass just like the example. While embedding/displaying/commenting has no problems, I can't see the admin panel correctly.

I assume I need to see it directly at http://my.server.ip.address:bindport but this is not possible while you bind the service on localhost. If I try to go /comment-engine/ url, I see a half-page, giving some info without authentication but that is all.

You can see it [here](https://gurkan.in/comment-engine/)

Here is my nginx config:
```
        location /comment-engine/ {
            proxy_pass http://127.0.0.1:9898/;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            add_header Cache-Control 'no-cache' always;
            expires off;
        }
```

Thanks.

**Comment by vkuznecovas** [comment]
This is definitely a bug, I'll try and take a look when I do have the time

**Comment by vkuznecovas** [comment]
Fixed it, as the readme states in #68 
You have two options:
* Build mouthful yourself, and when building the admin panel, which is running the npm run build inside the admin folder, specify an env variable called `HOMEPAGE`. For the example above it would be like so: `HOMEPAGE=/mouthful-demo/ npm run build`.
* Specify the path variable in config inside the API section. `"api":"/mouthful-demo/"` for  for the example above.

**Comment by seqizz** [comment]
Hi again,

Thanks. I've tried with latest release binary, considering it has the fix (Also since proxying would be a common use case, I guess self building might not be an option for everyone). Added following line to config.json under api segment:

```
"path":"/comment-engine/",
```

since I use that path to serve. Started without problems, but nothing changed for admin panel URL. You can check from the test link above again.

**Comment by vkuznecovas** [comment]
I've updated the docs to reflect that.

**Comment by vkuznecovas** [comment]
```
"moderation": {
        "enabled": true,
        "adminPassword": "somepassword",
        "sessionDurationSeconds": 21600,
        "maxCommentLength": 10000,
        "maxAuthorLength": 35,
        "path": "/"        
    },
```

**Comment by seqizz** [comment]
¡Ay, caramba! now everything works :+1: 
I'll be back with more suggestions, but this is for me a complete usable program now. Thanks for this :medal_military:
