### ISSUE TITLE
403 forbidden issue. The comments are temporarily unavailable

### ISSUE THREAD

**Issue by leem32** [vkuznecovas/mouthful#91]
Running Vagrant/Virtual box provider.
Centos 7 OS
Nginx server

I'm getting 403 Forbidden messages for a couple of files.
Steps I've taken so far.
1. I've extracted the archive into my root dir
2. Run the mouthful binary
3. added code to webpage e.g
`<div id="mouthful-comments" data-url="http://10.0.0.0:8080"></div>`
`<script src="http://10.0.0.0:8080/client.js"></script>`
(10.0.0.0 is my privare IP address in Vagrant)

When I reload the page I get the message: "The comments are temporarily unavailable".
In dev tools it show a 200 response code for client.js and a url `blob:http://10.0.0.0/f052827d-fa98-421c-bf3c-ba46881a7779`, but for `http://10.0.0.0:8080/v1/client/config` and `http://10.0.0.0:8080/v1/comments?uri=%2Fcomments-testing.php` it says 403 Forbidden.

I already have selinux switched off and I've also tried switching off my firewall to no avail.

Maybe this is a problem with nginx??
I added (tried each location):
```
    # location /mouthful {    
    # location /static {    
    # location /data {    
    proxy_pass http://172.17.0.1:1224/;    
     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;    
     proxy_set_header Host $host;    
     proxy_set_header X-Forwarded-Proto $scheme;    
    add_header Cache-Control 'no-cache' always;    
     }
```

I'm all out of ideas now, so any help is greatly appreciated.
Thanks

**Comment by vkuznecovas** [comment]
This is caused by a cors issue, most likely.

Check your config.json for the cors section.

```
"cors": {
"enabled": true,
"allowedOrigins": [
"https://dizzy.zone"
]
},
```

You'll want to adjust the allowedOrigins part :)

**Comment by leem32** [comment]
Yep, that got it working. Thanks I left cors enabled and just added my virtual host domain name and that fixed it.
One more thing though. How do I get to the admin panel? I have moderation turned on, but can't find anything in the docs about how to get to the panel. I've already changed my password in config.

**Comment by vkuznecovas** [comment]
just open up http://10.0.0.0:8080/ in your browser

**Comment by leem32** [comment]
Working, thanks. There doesn't seem to be any more problems. 
I think I'm going to add my own styles though as the default styles are a little basic. 
Thanks for this btw it's nice and light which is exactly what I've been looking for.

**Comment by vkuznecovas** [comment]
Exactly why I did this, thanks for using!
