### ISSUE TITLE
Honeypot field not working?

### ISSUE THREAD

**Issue by leem32** [vkuznecovas/mouthful#96]
Is the honeypot field the email input field? I assume it is as it's `display: none;`. If I add text to the email input field and post the comment it still reaches my admin panel and after I confirm the comment it's added to the page.
I've set honeypot to true in config.json, but it's still not working.

**Comment by vkuznecovas** [comment]
I'll check it out.

**Comment by vkuznecovas** [comment]
Confirming it's a client side bug. The request that's being sent to the backend does not contain the email field.

**Comment by leem32** [comment]
Thanks. If I'm using the official build on docker hub will the update be automatic?

**Comment by leem32** [comment]
Seems to be working now. It still says 'In queue for moderation', but the comment doesn't reach the admin panel.

Here's the steps I used to update Mouthful:
     
     # update image
     sudo docker pull vkuznecovas/mouthful
     # stop mouthful using id or name
     sudo docker stop 4a0ee982737b
     # remove mouthful container
     # sudo docker rm 4a0ee982737b
     # run mouthful
     docker run -d --name mouthful -v /var/mouthful/:/app/data -p 8080:8080 vkuznecovas/mouthful
     # done
