### ISSUE TITLE
Admin panel textarea height

### ISSUE THREAD

**Issue by leem32** [vkuznecovas/mouthful#97]
In the admin panel the textarea height is only `40px`. If someone posts a huge comment, and you don't notice the scrollbar you could easily hit confirm on them. 
It's only my opinion, but I think it would be nice if the textarea in the admin panel was always the height of the content.

Edit: You could also add a `maxlength=""` to the comment textarea to help prevent users from posting huge comments.

**Comment by vkuznecovas** [comment]
I'm pretty much thinking of redesigning the whole panel someday, I do agree it's hideous and needs a proper look at. 
https://github.com/vkuznecovas/mouthful/issues/79 is the proper issue to file this under
