### ISSUE TITLE
CORS blocks confirming comments in admin panel

### ISSUE THREAD

**Issue by leem32** [vkuznecovas/mouthful#99]
I'd like to enable CORS, but when I do it's blocking me from confirming comments in the admin panel.
Everything else seems to work fine.

Error in dev tools: `Failed to load resource: the server responded with a status of 403 (Forbidden) :8080/v1/admin/comments:1`

I'm working on localhost with Vagrant. My virtual host is dev.example.com, which uses the IP address 10.0.0.0

I've tried ` "allowedOrigins": ["http://dev.example.com"]` and "allowedOrigins": ["http://10.0.0.0"]`.

Is this a bug?

**Comment by vkuznecovas** [comment]
what response are you getting from the backend?

**Comment by vkuznecovas** [comment]
Did I understand correctly - you can update/delete the comments, but not confirm?

**Comment by vkuznecovas** [comment]
try specifying the port: `"allowedOrigins": ["http://dev.example.com:8080"]` or `"allowedOrigins": ["http://10.0.0.0:8080"]``

**Comment by leem32** [comment]
They're not working either. They both return `Failed to load http://dev.example.com:8080/v1/client/config: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://dev.example.com' is therefore not allowed access. The response had HTTP status code 403.` and the comments fail to load.

**Comment by vkuznecovas** [comment]
I've just tested this locally. Works fine with `http://localhost:{PORT}` no matter what port I'm using, as long as I do set it correctly in the allowed origin. Make sure to restart the container between the tries?

**Comment by leem32** [comment]
Thanks, I've fixed it!
I just had to set both the admin url with it's port and the comments URL without port and now it works fine and comments are confirmed,

(sometimes I access my dev site from localhost not dev.example.com so I needed them in CORS too)
Example CORS: `"allowedOrigins": ["http://localhost", "http://localhost:8080", "http://dev.example.com", "http://dev.example.com:8080"]`

Thanks again for all your help. Hopefully I can leave you alone now :)

**Comment by vkuznecovas** [comment]
glad I could help! Do raise another one if you encounter any issues
